// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: "doc",
      label: "1.1 - Révision",
      id: "cours/revision",
    },
    {
      type: "doc",
      label: "1.2 - Mise en page (révision)",
      id: "cours/mise-en-page",
    },
    {
      type: "doc",
      label: "2.1 - Nav Recycler i18n",
      id: "cours/recycler-view",
    },
    {
      type: "doc",
      label: "2.2 - Nav Recycler i18n",
      id: "cours/recycler-view",
    },
    {
      type: "doc",
      label: "3.1 - Layouts",
      id: "cours/layout",
    },
    {
      type: "doc",
      label: "3.2 - Intégration / remise TP1",
      id: "cours/integration",
      className: "remise-tp1",
    },
    {
      type: "doc",
      label: "4.1 - Réseau",
      id: "cours/http",
    },
    {
      type: "doc",
      label: "4.2 - Réseau",
      id: "cours/http",
    },
    {
      type: "doc",
      label: "5.1 - Formatif (intra)",
      id: "cours/formatif-intra",
    },
    {
      type: "doc",
      label: "5.2 - Examen intra (20%)",
      id: "cours/examen",
      className: "examen",
    },
    {
      type: "doc",
      label: "6.1 - Serveur Spring Boot",
      id: "cours/spring",
    },
    {
      type: "doc",
      label: "6.2 - Cookies 🍪",
      id: "cours/cookies",
    },
    {
      type: "doc",
      label: "7.1 - Débogage serveur",
      id: "cours/debogage",
    },
    {
      type: "doc",
      label: "7.2 - Déploiement serveur",
      id: "cours/deploiement",
    },
    {
      type: "doc",
      label: "8.1 - Intégration client-server",
      id: "cours/integration",
      className: "remise-tp2",
    },
    {
      type: "doc",
      label: "8.2 - Erreurs: HTTP",
      id: "cours/erreur-http",
    },
    {
      type: "doc",
      label: "9.1 - Erreurs: GUI",
      id: "cours/erreur-gui",
    },
    {
      type: "doc",
      label: "9.2 - Spring Boot Java",
      id: "cours/spring-java",
    },
    {
      type: "doc",
      label: "10.1 - Spring Boot Java",
      id: "cours/spring-java",
    },
    {
      type: "doc",
      label: "10.2 - Spring Boot Java",
      id: "cours/spring-java",
    },
    {
      type: "doc",
      label: "11.1 - Spring Boot Java",
      id: "cours/spring-java",
    },
    {
      type: "doc",
      label: "11.2 - Attente serveur",
      id: "cours/attente-serveur",
    },
    {
      type: "doc",
      label: "12.1 - Sécurité - inject., crypto",
      id: "cours/injection",
    },
    {
      type: "doc",
      label: "12.2 - Cybersec - cont. d'accès",
      id: "cours/controle-acces",
    },
    {
      type: "doc",
      label: "13.1 - Orientation et Taille",
      id: "cours/orientation-taille",
    },
    {
      type: "doc",
      label: "13.2 - 🏴‍☠️ CTF",
      id: "cours/ctf",
    },
    {
      type: "doc",
      label: "14.1 - Causerie - DTO / Cookies",
      id: "cours/causerie-dto-cookie",
    },
    {
      type: "doc",
      label: "14.2 - Correction TP3",
      id: "cours/correction-tp3",
      className: "remise-tp3",
    },
    {
      type: "doc",
      label: "15.1 - Formatif (final)",
      id: "cours/formatif-final",
    },
    {
      type: "doc",
      label: "15.2 - Examen final (30%)",
      id: "cours/examen",
      className: "examen",
    },
  ],
  tp: [{ type: "autogenerated", dirName: "02-tp" }],
  recettes: [{ type: "autogenerated", dirName: "03-recettes" }],
};

module.exports = sidebars;
